export {default as Home} from './Home'
export {default as EveryProduct} from './EveryProduct'
export {default as SingleProduct} from './SingleProduct'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Cart} from './Cart'